plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "Alex"
email: iamyueqing@gmail.com
description: ""
github:
  username: iamyueqing
gitment:
    repo: iamyueqing.github.io
    client_id: b7281f23677a19de85d0
    client_secret: 6b471b4a4daf3ef0081a7b7845532017320e528a

url: "https://iamyueqing.github.io"
imgrepo: https://iamyueqing.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

